---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [develop]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [develop]

###############
# Set the Job #
###############
jobs:
  linters:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Lint LESS files
        uses: actions-hub/stylelint@v1.1.3
        env:
          PATTERN: "**/*.less"
